### ISSUE TITLE
LANG_KEYS Referenced Before Assignment

### ISSUE THREAD

**Issue by CLoutas** [rogermolas/csv-localizer#5]
I am trying to run the tool for the first time, and I'm getting the following error:

Start Localizing .... 
Generation output : Localisations/output
Traceback (most recent call last):
  File "/usr/local/bin/csv-localizer", line 210, in <module>
    main(args, loglevel)
  File "/usr/local/bin/csv-localizer", line 58, in main
    generate_keys(IN_PATH, OUTPUT_DIR, PLATFORM)
  File "/usr/local/bin/csv-localizer", line 105, in generate_keys
    start_localize_ios(source_path, allwrites, LANG_KEYS)
UnboundLocalError: local variable 'LANG_KEYS' referenced before assignment

I checked `/usr/local/bin/csv-localizer` and on line 10 I can see the following:
`LANG_KEYS = None  #static will change later`

Is there something missing here? How am I supposed to set `LANG_KEYS `?

**Comment by rogermolas** [comment]
@CLoutas did you follow the correct csv format?
https://github.com/rogermolas/csv-localizer/blob/master/sample.csv

**Comment by aayushi-singhal** [comment]
@rogermolas: I am facing same issue with sample.csv file as well. 
Error:
Traceback (most recent call last):
  File "/usr/local/bin/csv-localizer", line 271, in <module>
    main(args, loglevel)
  File "/usr/local/bin/csv-localizer", line 64, in main
    generate_keys(IN_PATH, OUTPUT_DIR, PLATFORM)
  File "/usr/local/bin/csv-localizer", line 115, in generate_keys
    start_localize_ios(source_path, allwrites, LANG_KEYS)
UnboundLocalError: local variable 'LANG_KEYS' referenced before assignment

**Comment by lawlietop123** [comment]
the same problem

**Comment by rogermolas** [comment]
> the same problem

I updated the master branch to support JSON, I've changed the `LANG_KEYS ` initialization hope this will fix the issues

**Comment by lawlietop123** [comment]
@rogermolas  I solve the problem ,  that doesn't need to assign filename, it will combine all csv file into one ,thank you
